if [[ -z "$XDG_CONFIG_HOME" ]]
then
        export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:=${HOME}/.config}
fi

if [[ -d "$XDG_CONFIG_HOME/zsh" ]]
then
        export ZDOTDIR=${ZDOTDIR:=${XDG_CONFIG_HOME}/zsh}
fi

source $ZDOTDIR/zshenv
source $ZDOTDIR/zshrc
